language: ruby
sudo: true
rvm:
  - 2.4.1

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - sudo apt-get install libcurl3-dev

before_script: bundle exec jekyll build

script: travis_retry bundle exec htmlproofer --url-ignore "/www.tomesh.net/,/tomesh.net/" ./_site

notifications:
  email: false